language:       ruby

install:
  # Install Jekyll and dependencies
  - bundle install
  - gem install jekyll bundler
script:
  - bundle exec jekyll build

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir:    docs
  on:
    branch:     master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
