# Building docs because GH Page is built using --safe
destination: docs

markdown:    kramdown
highlighter: rouge

permalink:   pretty

url:         https://cryptools.github.io/learn

plugins:
    - jekyll-babel
    - jekyll-minifier

appID: 1392983460
