# Building docs because GH Page is built using --safe
destination: docs

markdown:    kramdown
highlighter: rouge

permalink:   pretty

url:         cryptools.github.io/learn

plugins:
    - jekyll-babel
    - jekyll-minifier
